name: check
on:
  push:
  pull_request:
  schedule:
  - cron: 45 4 * * 5
jobs:
  check:
    runs-on: macos-latest
    strategy:
      matrix:
        ruby:
        - '2.4'
        - '2.5'
        - '2.6'
        - '2.7'
        - '3.0'
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
        bundler-cache: true
    - run: bundle exec rspec
